name: art_tensorflow
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - matplotlib
  - opencv
  - pandas
  - scikit-image
  - tqdm
  - urllib3
  - tensorflow-gpu=1.15.0
