name: art_tensorflow
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - matplotlib
  - opencv
  - pandas
  - pytorch
  - requests
  - scikit-image
  - scipy
  - torchvision
  - cudatoolkit=9.2
  - tqdm
  - urllib3
  - tensorflow-gpu=1.15
  - cuda100
